### ISSUE TITLE
spherical coordinate transformation

### ISSUE THREAD

**Issue by christopherlovell** [alejandrobll/py-sphviewer#24]
I'm a bit confused as to the spherical coordinate transformation in `Camera.py` ([here](https://github.com/alejandrobll/py-sphviewer/blob/master/sphviewer/Camera.py#L81)):

```
x0 = -self.__params['r']*(np.sin(self.__params['p']*np.pi/180.) *
                                       np.cos(self.__params['t']*np.pi/180.))
z0 = self.__params['r']*(np.cos(self.__params['p']*np.pi/180.) *
                                     np.cos(self.__params['t']*np.pi/180.))
y0 = self.__params['r']*np.sin(self.__params['t']*np.pi/180.)
```

Why is `x0` multiplied by `-1`? theta (`t`) and phi (`p`) also seem to have been mixed up.

As a demonstration, here's a short script that simply calculates the x,y,z components of three orthogonal vectors in spherical coordinates. The first transformation is the one I am more familiar with, and below is the transformation used here, but corrected (no -1, and phi and theta swapped). They now give identical results.

```
import numpy as np 

phi   = np.array([0, 0,       np.pi/2])
theta = np.array([0, np.pi/2, np.pi/2])

x = np.sin(theta) * np.cos(phi) 
y = np.sin(theta) * np.sin(phi) 
z = np.cos(theta) 

print("Result 1:\n",np.round([x,y,z],2).T,"\n") 

x_b = np.sin(theta) * np.cos(phi)  
y_b = np.sin(phi) 
z_b = np.cos(phi) * np.cos(theta) 

print("Result 2:\n", np.round([x_b,y_b,z_b],2).T, "\n")   
```

Output:

```
Result 1:
 [[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]] 

Result 2:
[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]
```

Unless I'm making some silly mistake I think this should be corrected to avoid confusion. I've made the change [here](https://github.com/christopherlovell/py-sphviewer) and can push if you want.

**Comment by christopherlovell** [comment]
I think this is a result of a more fundamental misunderstanding of how the camera rotations are handled in the scene (which don't seem to be in spherical coordinates, despite using theta and phi as variable names..). I'll close for now

**Comment by alejandrobll** [comment]
Thanks, Chris,
I think the transformation is correct, although this is not used anywhere for the construction of the image. 

As you say, the angles `t `and `p` used to construct the scene do not correspond to the usual spherical angles. The reason is that the default projection projects everything onto the default xy plane of the reference frame. Therefore, it is natural to consider two perpendicular rotations, one along the x-axis (this is the angle `t`), and another respect to the y-axis (this is `p`). Rotations along the z-direction are controlled by the `roll` angle. The `_get_camera` method does not take that angle into account because I never updated the function to do so, but this should also be included. Note again that this is not used anywhere.

So, I guess that if you want to achieve a spherical rotation, you should think that the angle `roll` is the spherical angle "phi", and the angle `t` is the usual "theta". Would this work?
