### ISSUE TITLE
The difference between python2 and python3

### ISSUE THREAD

**Issue by tekkamanmaverick** [alejandrobll/py-sphviewer#25]
Hi Alejandro,

When I want to add the colorbar to image made by py-sphviewer, I find there is a large difference between python2 and python3.  It's a difference of several orders of magnitude. So, which version shall I believe?

**Comment by alejandrobll** [comment]
Hi, may be you are using two different versions? One for python 2 and another one for python 3? There has been a change in recent versions in which the value per pixel corresponds to the surface density rather than projected mass. That could explain the differences. Please check with `sphviewer.__version__` and update to the latest version if needed.

**Comment by tekkamanmaverick** [comment]
Yes. I use two different version.  Version 1.2.0 for python2 and version 1.2.3 for python3.

**Comment by tekkamanmaverick** [comment]
What should I do if I want to plot column density map by the new version? Is the following correct?

qv = QuickView(pos, density*sl, sl, r='infinity', plot=False, logscale=False)
img = qv.get_image()
extent = qv.get_extent()
ax.imshow(img, extent=extent, origin='lower')

**Comment by tekkamanmaverick** [comment]
And what about mass-weighted temperature map?

**Comment by tekkamanmaverick** [comment]
The python2 is not supported any more. So, I move to python3. It is very pity that I can't repeat the previous results by the new version when I want to submit my manuscript.

**Comment by alejandrobll** [comment]
You can always downgrade the package to the version your script was made for. These are still available within pip.
