### ISSUE TITLE
Request: Combine gas and stars

### ISSUE THREAD

**Issue by christopherlovell** [alejandrobll/py-sphviewer#5]
It would be great to combine the gas and stars in the same render, is this possible? If not, any plans to include it?

**Comment by alejandrobll** [comment]
I don't think that it should be part of the "core" of sphviewer, but it could certainly be included as a tool. I have my own tools to do so, but I am not planning to release those soon, in part because the result depends strongly on the method used to blend the images, and I haven't had time to check different methods. Any suggestion in particular?

**Comment by christopherlovell** [comment]
Fair enough. I haven't put too much thought in to any particular method, bit naive with regards to what's possible. Would simply pasting the stars as point sources on the rendered gas work, with brightness as a function of distance from the camera? Or do you have to include the interaction of the stars and gas?

**Comment by alejandrobll** [comment]
Let me just think in a good way (with this I mean general and simple) to blend the images. The basic idea would consist in making two images, one of the gas and the other of the stars. The routine should ask for the two images and return a RGB (and eventually alpha) channels of the final image. I would be able to write a small routine to do so, but I need to find some time...

**Comment by christopherlovell** [comment]
Sounds like a good approach. I have time in the near future to take a look, will let you know how I get on

**Comment by alejandrobll** [comment]
Please check the new Blend.py tool that I've pushed to the repository. It is very primitive at this point, but it can probably illuminate your thoughts. Just do python Blend.py and see the example I've wrote. This is a disc inside a cube. The cube and the disc are rendered separately using the gist_heat and gist_stern colour maps respectively. Then, I blend the images using two different algorithms (Screen and Overlay). Note that there are plenty of different ways to do the same, and certain algorithms are better than others, depending on the  input images, and the desired output of course. 
Perhaps one final warning. Before trying to blend the images, you should ensure that they are normalized in the range [0,1], without alpha channel at the moment, and also you could get better results if you use your own customized color map. I would like to keep developing it in my spare time, but of course that any suggestion or collaboration is always welcome. 

![figure_1](https://cloud.githubusercontent.com/assets/7341581/17077539/80cb6388-50cb-11e6-9d73-88eb1de54022.png)

**Comment by christopherlovell** [comment]
I checked out the blend tool and it looks neat. I had an attempt myself and came out with something less sophisticated. It simply produces an RGBA array with the alpha value scaled to the RGB power, or cut above a certain limit. The results, on first impressions, don't look as good as the blend tool. However, the approach could still be of value for introducing RGBA arrays in to the blend pipeline. It basically allows you to skip the following step in the blend process,

```
image1 = cm.gist_heat(get_normalized_image(qv1.get_image()))[:,:,0:3]
```

and just call my `rgba_from_array` method with a given colourmap and normalisation. See [here](https://github.com/polyphant1/py-sphviewer/blob/master/sphviewer/tools/rgba_tools.py). 

![rgba_tools _test](https://cloud.githubusercontent.com/assets/4648092/17084605/ea72ab68-51b9-11e6-9960-3fd71deb5a68.png)

**Comment by alejandrobll** [comment]
Thanks, nice approach! I liked the way you managed to merge the images, but I think that the final image should be a unique RGB instead of two with different alpha values. Two reasons for that. 1) What if you want to save the image without going though imshow? for example, using plt.imsave? In practice this is a good feature as it does speed up the process of making movies a lot. 2) It would be desirable to preserve the colour of each individual image to some extent, which can be done with the Screen algorithm that I use. That's the main reason why I prefer to say that the process consist in "blending" the images instead of stacking them. 
I would definitely add a "rgba_from_array" method to the current Blend tool. Would you like to add it and do a pull request? Otherwise, don't worry, I would be able to do so. In addition, I think that it would be nice to have a feature to define a custom colour map easily, probably setting up the minimum and maximum hue value for each image? I have already a tool to get RGB from HSV, and I could work on it later.

**Comment by alejandrobll** [comment]
Also, I think that you could also add your own methods as a possibility as well, among the current Screen and Overlay, and many others that can be added. I think that the idea of the Blend tool is to have as many methods as possible to get different results.

**Comment by christopherlovell** [comment]
I've got a bit of time at the end of the week, will add an rgba method then, keep an eye out for a pull request!

**Comment by christopherlovell** [comment]
Just made a pull request #6 

Rather than creating a dedicated RGBA method I've just updated the Blend methods to accept RGBA arrays. Creating an RGBA is tied up with what colourmaps you wish to choose so it gets quite messy.

**Comment by alejandrobll** [comment]
Thanks, I'll work a little bit more on this to check whether the images are RGB or not, and in case they aren't, apply a default colour scheme to each one. I think this would be a nice feature for lazy users like me...
